### PR TITLE
1VDTkLFp: sign assembly v3.2.x

### PR DESCRIPTION
**Pull request by oleg-loop54**
Only signed assemblies of the same name can be loaded together in CLR (that is needed for our internal tests for different API versions).
This PR **will not be merged in**, it'll only be used to publish new version of package (v3.2.1, with signing info)

### CODE REVIEW

**Comment by loop-evgeny** [comment]
Do we want the two assemblies to have the same name, though? Maybe it's just as easy to rename the assembly, and that makes it clearer in the Engine.Test code, too?

**Comment by oleg-loop54** [comment]
I've solved assembly naming with `extern alias`. It's going to be like `V2::Loop54.Request` and `V3::Loop54.Http.RequestManager`. 
Those namespaces are cleanly separated in code - no single file would have both V2 and V3 aliases (that's easy to control since developer has to manually add `extern alias` to the top of file).

Also, there's going to be V4 later (quite possibly while tests still run V2 and V3), so it has a potential to turn into mess with all the renamings.

**Comment by loop-evgeny** [comment]
Is there a branch where I can see this `extern alias` thing in action? I've never used it myself.

Obviously we cannot merge this to master, but it might be nice to have "api-v2" branch and merge it into that? It will basically be like this feature branch, just with a nice name.

**Comment by oleg-loop54** [comment]
> Is there a branch where I can see this `extern alias` thing in action? I've never used it myself.

Take a look here: https://github.com/LoopFiftyFour/monorepo/pull/1109

**Pull request closed without merging**
